version: "3.2"

services:
  web:
    tty: true
    image: docker.io/bitnami/laravel:6.5.2-debian-9-r18
    # command: tail -F anything # use to force install composer from terminal
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=attendize
      - DB_PASSWORD=
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  worker:
    image: leen15/attendize:latest
    depends_on:
      - mariadb
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html
      - .:/var/www
  mariadb:
    ports:
      - 3306:3306
    image: "docker.io/bitnami/mariadb:10.2-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=attendize
      - MARIADB_PASSWORD=1234
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
  redis:
    image: redis
  dbmanager:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 300M

volumes:
  mysql-data:
